COPY  START 0
RDBUFF MACRO &INDEV, &BUFADR, &RECLTH
       CLEAR X
       CLEAR A 
       LDT   #4090
       TD    =X'&INDEV'
       MEND
WRBUFF  MACRO  &OUTDEV, &BUFADR, &RECLTH
        LDA PARA1
        ADD PARA2
        STA RESULT
        MEND

FIRST STL RETADR
CLOOP RDBUFF &F1, &BUFFER, &LENGTH
